### PR TITLE
Fix progress bar not updating

### LINKED ISSUE #131: Separate optimization process
An issue brought up by Melaine Baker via PR #117 

>When I tried to track the volume of the wrist, once I clicked ok in the
tracking dialog menu, the program would freeze and give an "Not responding"
error message at the top of the window. This window would close itself, then
I would hit "Tracking Dialog" in Autoscoper to try again and ran into the
same error. I closed the interface all together and redid the volume
realignment, clicked "Tracking Dialog", set up the tracking options, hit ok,
and ran into the same error. I also tried again several hours later and still
was getting a "Not responding" message.

### LINKED ISSUE #146: Tracking Progress bar
Using the Tracking Options Dialog:

There is a built in progress bar- but it does not give the user feedback during tracking

### PR DESCRIPTION
**Pull request by NicerNewerCar**
* Bug was caused by incorrect types being used (dividing two integers instead of two doubles)
* Bug was initially introduced during the initial implementation of the progress bar (See 681c3c7)
* Merging this PR will close #146 
* #131 Will be closed once the cancel button is working
image

### CODE REVIEW

**Comment by amymmorton** [comment]
Awesome @NicerNewerCar 
Progress Bar is working - as I tested however- I mistakenly selected 60 as the end frame instead of 30 - bc the UI is inacessible- there isn't anyway to abort your optimization if you've  chosen the wrong window.... new issue
workingPbar

**Review by amymmorton — APPROVED** [review]
Great - progress bar working !

File: autoscoper/src/ui/TrackingOptionsDialog.cpp [hunk 1]
```diff
@@ -144,8 +144,7 @@ void TrackingOptionsDialog::frame_optimize()
       mainwindow->setFrame(mainwindow->getTracker()->trial()->frame);
 
          //update progress bar
-
-         double value = abs(to_frame-from_frame) > 0 ? abs(frame-from_frame)/ abs(to_frame-from_frame) : 0;
+     double value = abs(to_frame-from_frame) > 0 ? (1.0*abs(frame-from_frame)) / (1.0*abs(to_frame-from_frame)) : 0;
```
Comment (jcfr) [inline autoscoper/src/ui/TrackingOptionsDialog.cpp:147]:
```suggestion
     double value = abs(to_frame - from_frame) > 0 ? fabs(frame - from_frame) / fabs(to_frame - from_frame) : 0;
```

**Review by jcfr — APPROVED** [review]
