### PR TITLE
BUG: Clip bounds of DRR projection to the bounds of the radiograph

### LINKED ISSUE #203: OpenCL Buffer Error
This error has been reported by Cesar and Dajung

```
Destination buffer does not have enough room!
```

https://github.com/BrownBiomechanics/Autoscoper/blob/794539cf53e79114091cc7cf3d7b08e1a78bd291/libautoscoper/src/gpu/opencl/OpenCL.cpp#L992-L999

### PR DESCRIPTION
**Pull request by NicerNewerCar**
After meeting with @amymmorton this approach may be the way to move forward. However, a deeper dive into the geometry and the projections will likely need to be done later on.

This PR introduces the following:
*  Computation of the bounds of the radiograph image on the film plane (located at z = -2 or 2 units in front of the camera)
* Checking that the 2D DRR image falls within the bounds of the radiograph
* Clipping the bounds of the 2D DRR image to be at most the bounds of the radiograph

Successfully merging this PR should close the following PRs and issues:
* Closes #203
* Closes #229
* Closes #211

### Images and Diagrams

PXL_20231108_195705752

 
| Position in Autoscoper | Left Cam | Right Cam | 
| --- | ---- | --- |
| image | image_cam04 image_cam05 | image_cam06 image_cam07 |

For the left and right cam columns, the top image is DRR bottom image is the radiograph. 

| Position in Autoscoper | Terminal |
| --- | --- |
| image | image |

### CODE REVIEW

File: libautoscoper/src/Camera.cpp [hunk 1]
```diff
@@ -442,8 +442,10 @@ namespace xromm
     if (fx == 0 || fy == 0) {
       throw std::runtime_error("Invalid camera parameters (fx or fy is zero)");
     }
+    // viewport_[0] and viewport[0]_ approximately describe the x and y viewport coordinates of the (0,0) pixel
```
Comment (amymmorton) [inline libautoscoper/src/Camera.cpp:445]:
```suggestion
    // viewport_[0] and viewport[_1] approximately describe the x and y viewport coordinates of the (0,0) pixel
```

File: libautoscoper/src/Tracker.cpp [hunk 2]
```diff
@@ -969,10 +973,53 @@ void Tracker::calculate_viewport(const CoordFrame& modelview,double* viewport) c
...
+      // This means that the min_max bbox is less than the rad image bounds in the x direction
+      return false;
+    }
+    if (min_max[1] < rad_min_max_film[1] && min_max[3] < rad_min_max_film[1]) {
+      // This means that the min_max bbox is less than the rad image bounds in the y direction
+      return false;
+    }
+
+    // clip min_max to rad_min_max_film
+    if (min_max[0] < rad_min_max_film[0]) {
```
Comment (amymmorton) [inline libautoscoper/src/Tracker.cpp:1005]: *not necessary* should min_max be renamed to drr_min_max to aid in clarity?

File: libautoscoper/src/Tracker.cpp [hunk 3]
```diff
@@ -969,10 +973,53 @@ void Tracker::calculate_viewport(const CoordFrame& modelview,double* viewport) c
...
 
+    double rad_min_x_y_cam_coords[3];
+    cam->coord_frame().inverse().point_to_world_space(&(cam->image_plane()[3]), rad_min_x_y_cam_coords);
+    double rad_max_x_y_cam_coords[3];
+    cam->coord_frame().inverse().point_to_world_space(&(cam->image_plane()[9]), rad_max_x_y_cam_coords);
+    double rad_min_max_film[4];
+    rad_min_max_film[0] = -2*rad_min_x_y_cam_coords[0]/rad_min_x_y_cam_coords[2];
+    rad_min_max_film[1] = -2*rad_min_x_y_cam_coords[1]/rad_min_x_y_cam_coords[2];
+    rad_min_max_film[2] = -2*rad_max_x_y_cam_coords[0]/rad_max_x_y_cam_coords[2];
+    rad_min_max_film[3] = -2*rad_max_x_y_cam_coords[1]/rad_max_x_y_cam_coords[2];
```
Comment (jcfr) [inline libautoscoper/src/Tracker.cpp:984]:
```suggestion
    double rad_min_max_film[4] = {
      rad_min_max_film[0] = -2 * rad_min_x_y_cam_coords[0] / rad_min_x_y_cam_coords[2],
      rad_min_max_film[1] = -2 * rad_min_x_y_cam_coords[1] / rad_min_x_y_cam_coords[2],
      rad_min_max_film[2] = -2 * rad_max_x_y_cam_coords[0] / rad_max_x_y_cam_coords[2],
      rad_min_max_film[3] = -2 * rad_max_x_y_cam_coords[1] / rad_max_x_y_cam_coords[2],
    };
```

File: libautoscoper/src/Tracker.cpp [hunk 4]
```diff
@@ -969,10 +973,53 @@ void Tracker::calculate_viewport(const CoordFrame& modelview,double* viewport) c
         }
     }
 
+    double rad_min_x_y_cam_coords[3];
```
Comment (jcfr) [inline libautoscoper/src/Tracker.cpp:976]:
```suggestion
    double rad_min_x_y_cam_coords[3] = {0.0};
```

File: libautoscoper/src/Tracker.cpp [hunk 5]
```diff
@@ -969,10 +973,53 @@ void Tracker::calculate_viewport(const CoordFrame& modelview,double* viewport) c
...
+    cam->coord_frame().inverse().point_to_world_space(&(cam->image_plane()[3]), rad_min_x_y_cam_coords);
+    double rad_max_x_y_cam_coords[3];
```
Comment (jcfr) [inline libautoscoper/src/Tracker.cpp:978]:
```suggestion
    double rad_max_x_y_cam_coords[3] = {0.0};
```

File: libautoscoper/src/Tracker.cpp [hunk 6]
```diff
@@ -969,10 +973,53 @@ void Tracker::calculate_viewport(const CoordFrame& modelview,double* viewport) c
         }
     }
 
+    double rad_min_x_y_cam_coords[3];
+    cam->coord_frame().inverse().point_to_world_space(&(cam->image_plane()[3]), rad_min_x_y_cam_coords);
```
Comment (jcfr) [inline libautoscoper/src/Tracker.cpp:977]:
```suggestion
    cam.coord_frame().inverse().point_to_world_space(&(cam.image_plane()[3]), rad_min_x_y_cam_coords);
```

File: libautoscoper/src/Tracker.cpp [hunk 7]
```diff
@@ -969,10 +973,53 @@ void Tracker::calculate_viewport(const CoordFrame& modelview,double* viewport) c
...
+    double rad_max_x_y_cam_coords[3];
+    cam->coord_frame().inverse().point_to_world_space(&(cam->image_plane()[9]), rad_max_x_y_cam_coords);
```
Comment (jcfr) [inline libautoscoper/src/Tracker.cpp:979]:
```suggestion
    cam.coord_frame().inverse().point_to_world_space(&(cam.image_plane()[9]), rad_max_x_y_cam_coords);
```

File: libautoscoper/src/Tracker.cpp [hunk 8]
```diff
@@ -628,7 +628,11 @@ std::vector <double> Tracker::trackFrame(unsigned int volumeID, double* xyzypr)
       // Calculate the viewport surrounding the volume
       // (1b)
       double viewport[4];
-      this->calculate_viewport(modelview, viewport);
+      if (!this->calculate_viewport(modelview, views_[i]->camera(), viewport)) {
```
Comment (jcfr) [inline libautoscoper/src/Tracker.cpp:631]:
```suggestion
      if (!this->calculate_viewport(modelview, *views_[i]->camera(), viewport)) {
```

File: libautoscoper/src/Camera.cpp (hunk 1 above)
Comment (jcfr) [inline libautoscoper/src/Camera.cpp:445]:
```suggestion
    // viewport_[0] and viewport[0]_ describe the x and y viewport coordinates of the (0,0) pixel
```

Comment (jcfr) [reply libautoscoper/src/Camera.cpp:445]: What is the rational for using "approximately" ?

File: libautoscoper/src/Camera.cpp [hunk 9]
```diff
@@ -442,8 +442,10 @@ namespace xromm
...
     viewport_[0] = -(2.0f*cx - size_[0]) / fx;
     viewport_[1] = -(2.0f*cy - size_[1]) / fy;
+    // viewport_[2] and viewport[3] approximately describe the width and height of the viewport
```
Comment (jcfr) [inline libautoscoper/src/Camera.cpp:448]:
```suggestion
    // viewport_[2] and viewport[3] describe the width and height of the viewport
```

File: libautoscoper/src/Camera.cpp (hunk 1 above)
Comment (NicerNewerCar) [reply libautoscoper/src/Camera.cpp:445]: Since the principal point (`cx`,`cy`) is not always halfway between 0 and size for each dimension. The computed point may not represent exactly the pixel (0,0).


PXL_20231109_201327915

**Comment by amymmorton** [comment]
I'm going to have to look furhter on Tues- film plane overlap of rad_min_max_film still looks odd in -1 -1 1 1 normalized space...

pr230

**Comment by NicerNewerCar** [comment]
Plotting the DRR, clipped DRR, and Radiograph positions on the film plan seems pretty reasonable to me.

Here is Cesars data:
image

| cam1 | cam2 |
| --- | --- |

Dajungs data:

image


| cam1 | cam2 |
| --- | --- |

**Comment by NicerNewerCar** [comment]
@jcfr @amymmorton I added the 8 corners of the drr as well as the 4 corners of the radiograph.
image

| cam1 | cam2 |
| --- | --- |

**Comment by jcfr** [comment]
Could you also update the table above with a row where the to include the (bounding box + partial volume) are represented ?

**Review by amymmorton — APPROVED** [review]

**Review by jcfr — APPROVED** [review]
