### PR TITLE
BUG: Fix getRandom() returning values above max limit

### LINKED ISSUE #217: PSO:: getRandom returns values above/below bounds?
current code:

`float getRandom(float low, float high)
{
  return low + (high - low + 1.0f)*(float)rand() / (RAND_MAX + 1.0f);
}`

This allows positions to be populated with values above and below the max/min:
exceedBoundsRand

### PR DESCRIPTION
**Pull request by NicerNewerCar**
* Closes #217 

| method/`rand()` return val | `0` | `RAND_MAX` |
| --- | ---- | --- |
| Old | `low ` | `≈(high+1)` *| 
| New | `low` | `high` |

*Since, previously, we were scaling by `RAND_MAX/(RAND_MAX+1)` the computed value is going to be extremely close to , but slightly lower, than `high+1`

### CODE REVIEW

**Review by amymmorton — COMMENTED** [review]
In 
`getRandomClamped()`

the RAND_MX is parsed as a float. Do we need to cast here ?

**Comment by NicerNewerCar** [comment]
> In `getRandomClamped()`
> 
> the RAND_MAX is parsed as a float. Do we need to cast here ?

Probably not since the result of a `float/int` operation will be a float. However, having the cast won't result in a slowdown since the cast operation is extremely fast and may even get optimized out by the compiler. Personally, I think it's nice to be explicit with types especially since `rand()` and `RAND_MAX` are defined as integers. See [cppref](https://cplusplus.com/reference/cstdlib/rand/).

File: libautoscoper/src/PSO.cpp [hunk 1]
```diff
@@ -38,7 +38,7 @@ void intializeRandom()
 
 float getRandom(float low, float high)
 {
-  return low + (high - low + 1.0f)*(float)rand() / (RAND_MAX + 1.0f);
+  return low + (high - low)*(float)rand() / (float)RAND_MAX;
```
Comment (jcfr) [inline libautoscoper/src/PSO.cpp:41]:
```suggestion
  return low + (high - low) * getRandomClamped();
```

Comment (jcfr) [reply libautoscoper/src/PSO.cpp:41]: Adding a table with before/after showing the computed value when `rand()` returns either `0` or `RAND_MAX` would be helpful too.

**Review by amymmorton — APPROVED** [review]

File: libautoscoper/src/PSO.cpp [hunk 2]
```diff
@@ -38,7 +38,7 @@ void intializeRandom()
 
 float getRandom(float low, float high)
 {
-  return low + (high - low + 1.0f)*(float)rand() / (RAND_MAX + 1.0f);
+  return low + (high - low) * getRandomClamped();
```
Comment (jcfr) [inline libautoscoper/src/PSO.cpp:41]: This is consistent with implementation of `vtkMinimalStandardRandomSequence::GetRangeValue(double rangeMin, double rangeMax)`[^1]

[^1]: https://github.com/Kitware/VTK/blob/fe0294298f14539349d251188984ab36a262d64b/Common/Core/vtkMinimalStandardRandomSequence.cxx#L85-L100

Comment (jcfr) [inline libautoscoper/src/PSO.cpp:41]:
```suggestion
if (low == high)
{
  return low;
}
else
{
  return low + getRandomClamped() * (high - low);
}
```
