### PR TITLE
BUG: Fix edge cases in Slerp

### LINKED ISSUE #275: SAM crashing during optimization
SAM has been crashing on me every time I attempt to optimize. Despite using a high-quality tracking file as an initial guess, the optimization process fails. It manages to optimize for several frames, but then crashes unexpectedly.

Capture
Capture2

### PR DESCRIPTION
**Pull request by NicerNewerCar**
Closes #275 
Regression initially introduced in 6b7ad8e. Slerp interpolation fails in some cases when t == 0 or t == 1

### CODE REVIEW

File: libautoscoper/src/Tracker.cpp [hunk 1]
```diff
@@ -952,6 +952,12 @@ bool Tracker::calculate_viewport(const CoordFrame& modelview, const Camera& came
     return false;
   }
 
+  // Check if min_max is unchanged from the initial values
+  if (min_max[0] == 1.0 && min_max[1] == 1.0 && min_max[2] == -1.0 && min_max[3] == -1.0) {
+    // This means that something went terribly wrong
```
Comment (jcfr) [inline libautoscoper/src/Tracker.cpp:957]: Can you update the message to be more specific ? Should an error be logged ?

File: math/Quaternion.hpp [hunk 2]
```diff
@@ -379,6 +379,10 @@ struct Quat
 
   friend Quat slerp(const Quat& p, const Quat& q, const T& t)
   {
+    if (t == T(0))
```
Comment (jcfr) [inline math/Quaternion.hpp:382]: Should this be done with `t < std::numeric_limits<T>::epsilon()` ?

File: math/Quaternion.hpp [hunk 3]
```diff
@@ -379,6 +379,10 @@ struct Quat
...
+      return p;
+    if (t == T(1))
```
Comment (jcfr) [inline math/Quaternion.hpp:384]: and this one with `t > (T(1) - std::numeric_limits<T>::epsilon())`?

File: math/Quaternion.hpp [hunk 4]
```diff
@@ -379,6 +379,10 @@ struct Quat
 
   friend Quat slerp(const Quat& p, const Quat& q, const T& t)
   {
+    if (t < std::numeric_limits<T>::epsilon())
+      return p;
+    if (t > std::numeric_limits<T>::epsilon())
```
Comment (jcfr) [inline math/Quaternion.hpp:384]: Shouldn't this be `t > (1.0 - std::numeric_limits<T>::epsilon())` ?

**Review by jcfr — APPROVED** [review]
