### PR TITLE
BUG: Fix incorrect conversion from viewport coordinates in tracker

### LINKED ISSUE #203: OpenCL Buffer Error
This error has been reported by Cesar and Dajung

```
Destination buffer does not have enough room!
```

https://github.com/BrownBiomechanics/Autoscoper/blob/794539cf53e79114091cc7cf3d7b08e1a78bd291/libautoscoper/src/gpu/opencl/OpenCL.cpp#L992-L999

### PR DESCRIPTION
**Pull request by NicerNewerCar**
* Closes #203 
* See https://github.com/BrownBiomechanics/Autoscoper/issues/203#issuecomment-1708834168 for the reasoning behind the changes.

### CODE REVIEW

File: libautoscoper/src/Tracker.cpp [hunk 1]
```diff
@@ -785,9 +789,9 @@ void Tracker::calculate_viewport(const CoordFrame& modelview,double* viewport) c
     for (int j = 0; j < 8; j++) {
 
         // Calculate the location of the corner in object space
-    corners[3 * j + 0] = (corners[3 * j + 0] - volumeDescription_[idx]->invTrans()[0]) / volumeDescription_[idx]->invScale()[0];
-    corners[3 * j + 1] = (corners[3 * j + 1] - volumeDescription_[idx]->invTrans()[1]) / volumeDescription_[idx]->invScale()[1];
-    corners[3 * j + 2] = (corners[3 * j + 2] - volumeDescription_[idx]->invTrans()[2]) / volumeDescription_[idx]->invScale()[2];
+        corners[3 * j + 0] = (corners[3 * j + 0] - volumeDescription_[idx]->invTrans()[0]) / volumeDescription_[idx]->invScale()[0];
```
Comment (jcfr) [inline libautoscoper/src/Tracker.cpp:792]: To ensure the git blame only reflects the introduced changes, let's avoid fixing the indent here.

We will use clang-format and perform a batch update along with updating [.git-blame-ignore-revs](https://github.com/BrownBiomechanics/Autoscoper/blob/main/.git-blame-ignore-revs)

File: libautoscoper/src/Tracker.cpp [hunk 2]
```diff
@@ -600,8 +600,12 @@ std::vector <double> Tracker::trackFrame(unsigned int volumeID, double* xyzypr)
       this->calculate_viewport(modelview, viewport);
 
       // Calculate the size of the image to render
```
Comment (jcfr) [inline libautoscoper/src/Tracker.cpp:602]:
```suggestion
      // Calculate the size of the image to render from camera viewport size.
      // For more details, see https://github.com/BrownBiomechanics/Autoscoper/issues/203
```

**Review by jcfr — APPROVED** [review]
